NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
HORIZON_URL="https://horizon.stellar.org"
HOME_DOMAIN="https://www.stellarasset.store"
VERSION="2.0.0"


ACCOUNTS=[
"GAEAR2DVKCOB3G3PIPPOS5EIVWSPBZL3YH2CZVNANVFZXHWYF32TPYYS",
"GABNJM3BS7UL2ESZ7XIWZ655CRZVGWK2SREUVZVBMWTN4XE7AKXL4YUJ",
]

[DOCUMENTATION]

ORG_NAME="AIROX is an AI-powered digital asset on Stellar"
ORG_URL="https://www.stellarasset.store"
ORG_LOGO="https://www.stellarasset.store/images/AIROX.png"
ORG_DESCRIPTION="AIROX is an AI-powered digital asset on Stellar, built for smart finance, autonomous trading, and next-gen DeFi integration."
ORG_OFFICIAL_EMAIL="AIROX@stellarasset.store"

[[CURRENCIES]]
code="AIROX"
issuer="GAEAR2DVKCOB3G3PIPPOS5EIVWSPBZL3YH2CZVNANVFZXHWYF32TPYYS"
display_decimals=5
desc="AIROX is an AI-powered digital asset on Stellar, built for smart finance, autonomous trading, and next-gen DeFi integration."
name="AIROX AI Token"
status="live"
image="https://www.stellarasset.store/images/AIROX.png"
fixed_number=10000000000

[[PRINCIPALS]]
email="AIROX@stellarasset.store"
twitter="AIROX"
instagram="AIROX"
linkedin="AIROX"
